# Generated by Django 4.0.6 on 2022-07-22 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='name')),
                ('price', models.FloatField(default=0, verbose_name='price')),
                ('reduction', models.FloatField(default=0, verbose_name='reduction')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('decription', models.TextField(blank=True, null=True, verbose_name='describe')),
                ('is_avtivated', models.BooleanField(default=False, verbose_name='is active')),
                ('is_stock', models.BooleanField(default=True, verbose_name='is stock')),
                ('main_image', models.ImageField(upload_to='image/product/main/%Y/%m/%d/%H/%M/%S/', verbose_name='main image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='update at')),
                ('categories', models.ManyToManyField(blank=True, to='store.category', verbose_name='categories')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='image/product/%Y/%m/%d/%H/%M/%S/', verbose_name='image link')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='name')),
                ('value', models.TextField(verbose_name='value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='store.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Characteristic',
                'verbose_name_plural': 'Characteristics',
            },
        ),
    ]
