# Generated by Django 4.0.6 on 2022-08-19 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('value', models.CharField(max_length=255, verbose_name='value')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_code', models.CharField(max_length=12, verbose_name='command code')),
                ('has_deliver', models.BooleanField(default=False, verbose_name='has deliver')),
                ('is_sell', models.BooleanField(default=False, verbose_name='is sell')),
                ('is_cancel', models.BooleanField(default=False, verbose_name='is cancel')),
                ('localisation_x', models.FloatField(default=0, verbose_name='localisation X')),
                ('localisation_y', models.FloatField(default=0, verbose_name='localisation Y')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'command',
                'verbose_name_plural': 'commands',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('price', models.FloatField(default=0, verbose_name='price')),
                ('reduction', models.FloatField(default=0, verbose_name='reduction')),
                ('description', models.TextField(blank=True, null=True, verbose_name='describe')),
                ('is_avtivated', models.BooleanField(default=False, verbose_name='is active')),
                ('recomended', models.BooleanField(default=False, verbose_name='recomended')),
                ('is_stock', models.BooleanField(default=True, verbose_name='is stock')),
                ('main_image', models.ImageField(upload_to='image/product/main/%Y/%m/%d/%H/%M/%S/', verbose_name='main image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='update at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, verbose_name='quantity')),
                ('ordered', models.BooleanField(default=False, verbose_name='ordered')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.command', verbose_name='command')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='image/product/%Y/%m/%d/%H/%M/%S/', verbose_name='image link')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('value', models.TextField(verbose_name='value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='store.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Characteristic',
                'verbose_name_plural': 'Characteristics',
            },
        ),
    ]
