# Generated by Django 4.0.6 on 2022-07-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_stock_alter_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('all', 'Tout'), ('man', 'Homme'), ('women', 'Femme'), ('cosmetic', 'Cosmetic'), ('children', 'Enfant'), ('electronic', 'Electronique')], max_length=255, verbose_name='categories'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
