# Generated by Django 4.0.6 on 2022-07-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_alter_characteristics_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(null=True, verbose_name='categoriy'),
        ),
    ]
