# Generated by Django 4.0.6 on 2022-07-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('all', 'Tout'), ('man', 'Homme'), ('women', 'Femme'), ('cosmetic', 'Cosmetic'), ('children', 'Enfant'), ('electronic', 'Electronique')], max_length=255, verbose_name='categoriy'),
        ),
    ]
