# Generated by Django 4.0.6 on 2022-08-10 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recomended',
            field=models.BooleanField(default=False, verbose_name='recomended'),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deliver', models.BooleanField(default=False, verbose_name='is deliver')),
                ('localisation_x', models.FloatField(default=0, verbose_name='localisation X')),
                ('localisation_y', models.FloatField(default=0, verbose_name='localisation Y')),
                ('oeders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='oeders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
