# Generated by Django 4.0.6 on 2022-08-17 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0011_product_recomended_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_code', models.CharField(max_length=12, verbose_name='command code')),
                ('has_deliver', models.BooleanField(default=False, verbose_name='has deliver')),
                ('is_sell', models.BooleanField(default=False, verbose_name='is sell')),
                ('is_cancel', models.BooleanField(default=False, verbose_name='is cancel')),
                ('localisation_x', models.FloatField(default=0, verbose_name='localisation X')),
                ('localisation_y', models.FloatField(default=0, verbose_name='localisation Y')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'command',
                'verbose_name_plural': 'commands',
            },
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.AddField(
            model_name='order',
            name='command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.command', verbose_name='command'),
        ),
    ]
