# Generated by Django 4.0.6 on 2022-08-19 13:59

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usermodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.userImage, verbose_name='image'),
        ),
    ]
